### ISSUE TITLE
Need password support

### ISSUE THREAD

**Issue by ghost** [sjiveson/nfs-server-alpine#15]
I am currently running nfs server with this image, exposing port 2049 to public internet.
With no authorization process, anyone can mount it, that is not a situation we want.
So can you please add passord support to this image, so we can pass the password in the container with a environment or in some other form ?
e.g.
```
nfs:
  image: itsthenetwork/nfs-server-alpine:latest
  privileged: true
  ports:
    - 2049:2049
  volumes:
    - ~/nfs:/nfsshare
  environment:
    - SHARED_DIRECTORY=/nfsshare
#    - PASSWORD=password
```
