### ISSUE TITLE
Fails on raspberry zero w

### ISSUE THREAD

**Issue by AnderssonPeter** [sjiveson/nfs-server-alpine#19]
Hi im trying to use this container using docker-compose
```yaml
  nfsserver:
    image: itsthenetwork/nfs-server-alpine:9-arm
    restart: unless-stopped
    volumes:
      - /data/share:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      SHARED_DIRECTORY: /share
      READ_ONLY: 'true'
    privileged: true
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"
```
using the same setup on a pi3 works.

log:
```bash
The PERMITTED environment variable is missing or null, defaulting to '*'.
Any client can mount.
The SYNC environment variable is missing or null, defaulting to 'async'.
Writes will not be immediately written to disk.
Starting Confd population of files...
/usr/bin/nfsd.sh: line 91:     7 Illegal instruction     (core dumped) /usr/bin/confd -version

Displaying /etc/exports contents...
/usr/bin/nfsd.sh: line 91:     8 Illegal instruction     (core dumped) /usr/bin/confd -onetime
# /etc/exports
#
# See exports(5) for a description.

# use exportfs -arv to reread
#/export    192.168.1.10(rw,no_root_squash)


Starting rpcbind...
Displaying rpcbind status...
   program version netid     address                service    owner
    100000    4    tcp6      ::.0.111               -          superuser
    100000    3    tcp6      ::.0.111               -          superuser
    100000    4    udp6      ::.0.111               -          superuser
    100000    3    udp6      ::.0.111               -          superuser
    100000    4    tcp       0.0.0.0.0.111          -          superuser
    100000    3    tcp       0.0.0.0.0.111          -          superuser
    100000    2    tcp       0.0.0.0.0.111          -          superuser
    100000    4    udp       0.0.0.0.0.111          -          superuser
    100000    3    udp       0.0.0.0.0.111          -          superuser
    100000    2    udp       0.0.0.0.0.111          -          superuser
    100000    4    local     /var/run/rpcbind.sock  -          superuser
    100000    3    local     /var/run/rpcbind.sock  -          superuser
Starting NFS in the background...
rpc.nfsd: knfsd is currently down
rpc.nfsd: Writing version string to kernel: -2 -3 +4
rpc.nfsd: Created AF_INET TCP socket.
rpc.nfsd: Created AF_INET6 TCP socket.
Exporting File System...
exportfs: No file systems exported!
Starting Mountd in the background...
Startup successful.
```

im using hypriot os on both units, the pi zero is using a somewhat older version.
